version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Backend/RestService/Dockerfile.app
    depends_on:
      - db
    ports:
      - "5000:5000"
    command: ["python3", "RestService.py"]
    container_name: flask-rest-api
    networks:
      - localnetwork
      
  db:
    image: postgres
    volumes:
      - ./Backend/Database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    container_name: local_db
    networks:
      - localnetwork

  scanner:
    build:
      context: .
      dockerfile: ./Backend/Scanner/Dockerfile
    depends_on:
      - app
    command: ["python3", "scanner.py"]
    container_name: scanner
    volumes:
      - ./Backend/Scanner:/app
    network_mode: "host"
    
networks:
  localnetwork:

